**1. Cree un programa que selecciones dos vectores de longitud
n (dada por el usuario al principio) y halle su producto
escalar.**

In [5]:
n = int(input("Ingresa la longitud de los vectores: "))


vector1 = []
vector2 = []


print("Ingresa los elementos del primer vector:")
for i in range(n):
    elemento = int(input())
    vector1.append(elemento)


print("Ingresa los elementos del segundo vector:")
for i in range(n):
    elemento = int(input())
    vector2.append(elemento)


producto_escalar = 0
for i in range(n):
    producto_escalar += vector1[i] * vector2[i]


print("El producto escalar es:", producto_escalar)


Ingresa la longitud de los vectores: 2
Ingresa los elementos del primer vector:
1
2
Ingresa los elementos del segundo vector:
1
2
El producto escalar es: 5


**2. Cree un programa que solicite dos matrices A y B (las
dimensiones de cada matriz deben ser indicadas por el
usuario) y, de ser posible, realice las siguientes operaciones:
a) 3A
b) 4B
c) A + B
d) B × A**

In [8]:
import numpy as np


fila_A = int(input("Ingrese el número de filas de la matriz A: "))
col_A = int(input("Ingrese el número de columnas de la matriz A: "))
fila_B = int(input("Ingrese el número de filas de la matriz B: "))
col_B = int(input("Ingrese el número de columnas de la matriz B: "))


A = np.zeros((fila_A, col_A))
B = np.zeros((fila_B, col_B))

for i in range(fila_A):
    for j in range(col_A):
        A[i][j] = float(input(f"Ingrese el valor para A[{i+1}][{j+1}]: "))

for i in range(fila_B):
    for j in range(col_B):
        B[i][j] = float(input(f"Ingrese el valor para B[{i+1}][{j+1}]: "))


tresA = 3*A
cuatroB = 4*B
suma = A + B
multiplicacion = np.dot(B, A)


print("3A:")
print(tresA)

print("4B:")
print(cuatroB)

print("A + B:")
print(suma)

print("B x A:")
print(multiplicacion)



Ingrese el número de filas de la matriz A: 2
Ingrese el número de columnas de la matriz A: 2
Ingrese el número de filas de la matriz B: 2
Ingrese el número de columnas de la matriz B: 2
Ingrese el valor para A[1][1]: 1
Ingrese el valor para A[1][2]: 2
Ingrese el valor para A[2][1]: 3
Ingrese el valor para A[2][2]: 4
Ingrese el valor para B[1][1]: 1
Ingrese el valor para B[1][2]: 2
Ingrese el valor para B[2][1]: 3
Ingrese el valor para B[2][2]: 4
3A:
[[ 3.  6.]
 [ 9. 12.]]
4B:
[[ 4.  8.]
 [12. 16.]]
A + B:
[[2. 4.]
 [6. 8.]]
B x A:
[[ 7. 10.]
 [15. 22.]]
